### ISSUE TITLE
ArangoDB 3.6.5 Swagger Error?

### ISSUE THREAD

**Issue by Phillips126** [arangodb/arangodb#12297]
## My Environment

* __ArangoDB Version__:        

- [x] 3.6.5

* __Storage Engine__:             

- [x] RocksDB

* __Deployment Mode__:       
- [x] Single Server
* __Deployment Strategy__:   
- [x] Manual Start
* __Configuration__:               
- [x] Running as service with self-signed certs (dev environment)
* __Infrastructure__:               
* __Operating System__:        
- [x] Windows 10
* __Total RAM in your machine__:        
- [x] 32Gb
* __Disks in use__:        
- [x] SSD
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

- [x] Foxx

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Write Foxx app, (works on 3.6.4)
2. Load Foxx app into 3.6.5 ArangoDB
3. Open newly added service, click "API" tab

__Problem__:

I have the database called:  "ticketing" and an endpoint "/api".
I've uploaded my working Foxx app into ArangoDB 3.6.5 (upgraded from 3.6.4) and the Swagger API is not displaying.
Instead, I am left with a blank page, console logs the following error:

> GET https://localhost:8529/_db/ticketing/api 404 (Not Found)

> Uncaught TypeError: e.indexOf is not a function
>     at C.fn.init.C.fn.load (jquery.js:9034)
>     at new C.fn.init (jquery.js:2743)
>     at e (jquery.js:128)
>     at r.changeSubview (applicationDetailView.js:83)
>     at HTMLDivElement.dispatch (jquery.js:4668)
>     at HTMLDivElement.m.handle (jquery.js:4488)

Under the "Info" tab, the Foxx app is pointing to the correct location:

`C:\ProgramData\ArangoDB-apps\_db\ticketing\api\APP`

NOTE: The Foxx app DOES still work, it just does not display the swagger information.
Clicking the "Swagger" button on the "API" page displays the JSON that does appear to be intact.

__Expected result__:

Swagger API endpoints to display as they did in 3.6.4.
I will be able to test them from the Web UI.

**Comment by dothebart** [comment]
Hi, 
the error message you posted seems to originate within the swagger UI - not aardvark itself. 
Are you able to share the swagger.json generated by the foxx framework? 
Or load it into the [swagger editor](https://editor.swagger.io/) to see if there are any errors in the generated json?

**Comment by Phillips126** [comment]
Thank you for helping me look into this problem.
Here is my swagger.json (which is very much a work in progress):
https://pastebin.com/ZViFSjwL

I pasted the JSON into the swagger editor you linked.  After converting to YAML automatically, it didn't seem to like the:  `schema.pattern: []` or `schema.properties.error.anyof: ...`

**Comment by Calrain** [comment]
I have the same issue, with ArangoDB 3.6.5 on Windows Server 2016.

I commented out all my routes so that I had no endpoints defined at all, and it still showed a blank API tab in the Service UI.

When I clicked on the [Swagger] button in the top right, this was the JSON payload:
```
{
	"swagger": "2.0",
	"basePath": "/_db/mydatabase/myservice",
	"paths": {},
	"info": {
		"title": "myservice",
		"description": "My Serivce",
		"version": "1.0.0",
		"license": {
			"name": "Commercial"
		}
	}
}
````

I pasted this into an online swagger editor and it validated OK, and showed an expected rendering of the swagger output which shows the basePath, and has a message that no endpoints are defined.

In ArangoDB UI on the Service API tab, I get a grey screen with only a [Swagger] button in the top right.

In the browser console window I get the same e.indexOf error as is shows above.

**Comment by tobi-or-not-tobi** [comment]
I'm experiencing the same issue. I'm new to arangoDb and was listening to an older video (https://www.youtube.com/watch?v=on1l2pEEWnw&t=1541s) and tried to create a new foxx service. 

I'm seeing a blank screen when I navigate to the API tab of the newly created service, and see 2 console errors :

1. `jquery.js:8815 GET http://127.0.0.1:8529/_db/_system/test 404 (Not Found)`. 
I believe is is kind of an expected error (according to https://stackoverflow.com/questions/53840307/arangodb-getting-started-with-foxx-microservices-404-errormessage-unknown-pa)

2. jquery error: 
```
jquery.js:9034 Uncaught TypeError: e.indexOf is not a function
    at C.fn.init.C.fn.load (jquery.js:9034)
    at new C.fn.init (jquery.js:2743)
    at e (jquery.js:128)
    at r.changeSubview (applicationDetailView.js:83)
    at HTMLDivElement.dispatch (jquery.js:4668)
    at HTMLDivElement.m.handle (jquery.js:4488)
```

I'm running a local instance on mac.

**Comment by jsteemann** [comment]
Should be fixed via the above PRs. The bugfix can hopefully be released with 3.6.6.

**Comment by tobi-or-not-tobi** [comment]
Thanks for unblocking me, I was able to hack your fix into the js chunk. Swagger docs is working again.

**Comment by jsteemann** [comment]
@tobi-or-not-tobi : Thanks for the confirmation!

**Comment by Phillips126** [comment]
Thanks for the quick resolution guys.  Since I consider this feature to be "bonus" and doesn't effect my use of the database, I'll just await the patched 3.6.6.  Incredible database you folks have developed and great support on top.  Keep up the good work!
