### ISSUE TITLE
Creating package (ebuild) for Gentoo Linux: request for information

### ISSUE THREAD

**Issue by equaeghe** [arangodb/arangodb#11467]
## My Environment

* __ArangoDB Version__: 3.7.0
* __Operating System__: Gentoo
* __Used Package__: sources

## Component, Query & Data

__Affected feature__: Installation

__Problem__: I am trying to create a Gentoo package (ebuild) for arangodb (version 3.7.0). I would like to get information about dependencies that I should encode in the ebuild and help in fixing issues that I encounter.

So my first request is: _Where can I find (or what are) all the requirements to successfully compile and run arangodb?_ I have consulted the [debian compilarion instructions](https://www.arangodb.com/docs/stable/installation-compiling-debian.html), the [CMakeLists.txt file](https://github.com/arangodb/arangodb/blob/v3.7.0/CMakeLists.txt), the [CHANGELOG](https://github.com/arangodb/arangodb/blob/v3.7.0/CHANGELOG), the [VERSIONS](https://github.com/arangodb/arangodb/blob/v3.7.0/VERSIONS) file, and an [old ebuild that someone once made for 3.2.10](https://github.com/gbevan/portage-arangodb-overlay/blob/master/dev-db/arangodb3/arangodb3-3.2.10.ebuild). However, possibly due to lack of experience, this still gives me a fragmented understanding.

My second request is more concrete. [I have created an ebuild](https://bugs.gentoo.org/718060), but it fails with the following error:
```
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:21 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4",
  but required is exact version "3"
  (found /var/tmp/portage/dev-db/arangodb-3.7.0/temp/python2.7/bin/python3)
```
This indicates some misspecification in the ebuild on my part, but I do not know how to fix it. If someone knows what is causing this, this might help me fix it.

**Comment by dothebart** [comment]
Hi, 
regarding the python interpreter - this should now work with a python 3 as of the 3.7.Alpha/.. . 
You may need to flush previously existing cmake-cache files in the build folder; You may need to specify the python interpreter using `-DPYTHON_EXECUTABLE=/usr/bin/python3` to make sure that the proper version is picked. 
`arangodb-3.7.0/temp/python2.7/bin/python3` sounds to me as if its mixing up something?

**Comment by equaeghe** [comment]
> regarding the python interpreter - this should now work with a python 3 as of the 3.7.Alpha/.. .

Which versions (≥, ≤)? 

> `arangodb-3.7.0/temp/python2.7/bin/python3` sounds to me as if its mixing up something?

Yes, but I have no clue what is the reason. I will try to get help if moving to Python 3.y does not help.

**Comment by equaeghe** [comment]
Moving to requiring Python 3 fixed the error I saw. I now got past the configure stage, albeit with various warnings. At that point, the build process bails out with the following error:
```
ninja: error: build.ninja:1272: bad $-escape (literal $ must be written as $$)
```

Perhaps I should first deal with the following warnings:
```
-- Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS)
```
```
-- Could NOT find BFD (missing:  BFD_INCLUDE_DIR BFD_SHARED_LIBS BFD_STATIC_LIBS BFD_INCLUDE_DIR_ANSIDECL BFD_INCLUDE_DIR_BFD BFD_SHARED_LIB BFD_STATIC_LIB BFD_STATIC$
BFD_INCLUDE_DIR:
BFD_LIBRARY_DIR:
BFD_SHARED_LIBS:
BFD_STATIC_LIBS:
BFD_SHARED_LIB_RESOURCES:
```
```
-- Could NOT find Unwind (missing:  Unwind_INCLUDE_DIR Unwind_SHARED_LIBS Unwind_STATIC_LIBS UNWIND_SHARED_LIBRARY_CORE UNWIND_STATIC_LIBRARY_CORE UNWIND_SHARED_LIBRA$
Unwind_INCLUDE_DIR: Unwind_INCLUDE_DIR-NOTFOUND
Unwind_LIBRARY_DIR:
Unwind_SHARED_LIBS:
Unwind_STATIC_LIBS:
Unwind_SHARED_LIB_RESOURCES:
```
```
LZMA shared library not found. Required if during linking the following errors are seen: undefined reference to `lzma_...
LZMA static library not found. Required if during linking the following errors are seen: undefined reference to `lzma_...
```
```
CMake Warning:
  Manually-specified variables were not used by the project:

    ETCDIR
    VARDIR
```
Any input on these warnings is welcome.

**Comment by dothebart** [comment]
sorry, ninja cannot be supported at the time being because of https://github.com/ninja-build/ninja/issues/1139  - use make. Tbh. I really find its a pitty that they didn't make it to implement such a relatively simple features in mainline ninja in 5 years. 

Python 3 is to be used from the to be released 3.7 onwards. 

Thanks for your efforts.

**Comment by equaeghe** [comment]
> sorry, ninja cannot be supported at the time being because of [ninja-build/ninja#1139](https://github.com/ninja-build/ninja/issues/1139) - use make.

OK, using emake was easy thanks to functionality present in the Gentoo ebuild ecosystem. It compiles, but I now have a problem during linking:
```
[…]
Linking CXX executable ../bin/arangod
[…]
lto-wrapper: fatal error: write: No space left on device
```

I'm building in a tmpfs of about 11 GB. Is that insufficient?

**Comment by equaeghe** [comment]
There are quite a number of bundled (3rdparty) packages such as zlib, lz4, nghttp, boost,… Many are also available in Gentoo. I'd like to try and unbundle them. Do you know how I should do this? (I have very little experience building large software packages.)

**Comment by graetzer** [comment]
That’s a significant effort and probably a bit of a time sink without experience

**Comment by equaeghe** [comment]
>> There are quite a number of bundled (3rdparty) packages such as zlib, lz4, nghttp, boost,… Many are also available in Gentoo. I'd like to try and unbundle them. Do you know how I should do this? […]

> That’s a significant effort and probably a bit of a time sink without experience

Unless pointing to or providing instructions are the big time sink, I'm still interested. I can retreat once I understand the effort involved, or not.

**Comment by graetzer** [comment]
I guess you need to rewrite the build system so it uses dynamic linking. Some dependencies like v8 are patched and we are on specific versions

**Comment by dothebart** [comment]
LTO is needed to produce production grade binaries - and yes, this *is* very resource hungry. 

the bundling of the 3rd party is in `3rdParty/CMakeLists.txt`. Please note that our CI, QA etc. run on the exact versions included therein, and older / newer system libraries may not even compile, or produce bugs not known to us - which would then make e-build compiled binaries basically unsupporteable. 

There also may be bugfixes or adjustments done by us to adapt the packages to our needs (usually noted in 3rdParty/README_maintainers.md ) 

The main compilation work is in V8, iresearch, rocksdb and S2 - which all again are pretty version dependent - and most probably won't be lingering around compiled in other dependencies on users disks.

Hence I'd strongly disadvice to attempt unbundling. If you feel that a newer version should be used, rather send a PR.

**Comment by equaeghe** [comment]
> LTO is needed to produce production grade binaries - and yes, this _is_ very resource hungry.

Ok, before moving to production-ready, I'll go for ‘it compiles’. _I'll have to disable LTO for now. is there a configuration switch?_ (Unbundling efforts will not start before I have a working build.)

> the bundling of the 3rd party is in `3rdParty/CMakeLists.txt`. Please note that our CI, QA etc. run on the exact versions included therein, and older / newer system libraries may not even compile, or produce bugs not known to us - which would then make e-build compiled binaries basically unsupporteable.

I understand your point of view. You have no obligation to support Gentoo users. Nevertheless, Gentoo has a strong opinion on bundling. (Fedora is similar, BTW.) Please see https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies and the links at the end of that page to understand the distribution's perspective. As a consequence, bundled libraries block packages from being supported by Gentoo.

An ebuild can specify version constraints on dependencies. As long as only the public API of libraries is used by arangodb, compatibility should be quantifiable that way. Gentoo can provide multiple versions of the same library as needed for applications depending on different versions.

> The main compilation work is in V8, iresearch, rocksdb and S2 - which all again are pretty version dependent - and most probably won't be lingering around compiled in other dependencies on users disks anyways.

These are not in the Gentoo package repository, so aren't prime candidates for unbundling.

**Comment by equaeghe** [comment]
> > LTO is needed to produce production grade binaries - and yes, this _is_ very resource hungry.
> 
> […] _I'll have to disable LTO for now. is there a configuration switch?_ […]

`-DUSE_IPO=OFF` appears to work…

**Comment by equaeghe** [comment]
Even without IPO/LTO building requires a lot of space (~12 GB). In any case, I'm now encountering an error during the install phase:
```
newinitd: /var/tmp/portage/dev-db/arangodb-3.7.0/files/arangodb3.initd does not exist
```
Any ideas?

**Comment by equaeghe** [comment]
I managed to get it to compile and install. (It needed about 12 GB of disk space, without LTO!) Before I can test running, I need to fix the etc and var location. Currently these are at `/usr/etc` and `/var/etc`, but they need to be at `/etc` and `/var`. Are there any cmake switches I can use? An earlier ebuild used `-DETCDIR=/etc` and `-DVARDIR=/var`, but these are unknown for 3.7.0.

**Comment by dothebart** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/arangodb.rb probably has all you need - Also the go receipie for the arangodb starter.

**Comment by dothebart** [comment]
Hey, @equaeghe did you get it working? Should we link the ebuild somewhere? 
Do we still need this issue open?

**Comment by equaeghe** [comment]
> Hey, @equaeghe did you get it working? […]

Not yet, I had trouble with the `/etc` and `/var` location and then a lack of time. Not much has happended since my last message.

> Do we still need this issue open?

It would be a convenient tracker for me. In case you prefer separate issues for each step, you can close this. In case it is distracting by being open, you can close it and I will comment whenever comes up, allowing you to reopen as needed.

**Comment by dothebart** [comment]
ok, just wanted to check back. 
Can you post the relevant parts of your cmake configure invocation? maybe I can help.

**Comment by equaeghe** [comment]
Well, I said before that I managed to get a complete build. That isn't working anymore and I do not know why. I get
```
[…]
[ 20%] Built target v8_build
make[1]: Leaving directory '/var/tmp/portage/dev-db/arangodb-3.7.0/work/arangodb-3.7.0_build'
make: *** [Makefile:152: all] Error 2
[…]
```
I need to get it to build again before I move on. I'm trying to create the exact conditions I had two weeks ago…

**Comment by equaeghe** [comment]
> I need to get it to build again before I move on. I'm trying to create the exact conditions I had two weeks ago…

It was a missing Python dependency. I want to try one more thing later today and then get back to sorting out the `/var` and `/etc` issue.

**Comment by equaeghe** [comment]
Ok, a little progress. I managed to get the build to use `/var` instead of `/usr/var` by including `DCMAKE_INSTALL_LOCALSTATEDIR=/var` in the local cmake arguments. However, for `/etc` I didn't yet manage, `-DCMAKE_INSTALL_SYSCONFIG=/etc` didn't work. I got the messages:
```
The ebuild is installing to one or more unexpected paths:    
                                                             
  /usr/etc                                                   
                                                             
Please fix the ebuild to use correct FHS/Gentoo policy paths.
```
```
One or more CMake variables were not used by the project:
  CMAKE_INSTALL_SYSCONFIG                                
```
*Do you have any idea how I can convince cmake to use `/etc`?*

Concerning the content of `/var/arangodb3`, I got the message:
```
One or more empty directories installed to /var:                     
                                                                     
  /var/lib/arangodb3                                                 
  /var/lib/arangodb3-apps                                            
  /var/log/arangodb3                                                 
                                                                     
If those directories need to be preserved, please make sure to create
or mark them for keeping using 'keepdir'. Future versions of Portage 
will strip empty directories from installation image.                
```
*Am I correct to assume that these directories should indeed be preserved?*

**Comment by dothebart** [comment]
https://github.com/arangodb/oskar/blob/master/scripts/buildArangoDB4.fish is used for configuring the packages 

All that I see to that regard there is: 
` -DCMAKE_INSTALL_PREFIX=/ `

The `/var/lib|log` directories need to be there - yes. and they need to be writeable by the `arangod` daemon.

**Comment by equaeghe** [comment]
> All that I see to that regard there is:
> `-DCMAKE_INSTALL_PREFIX=/`

And that is what was needed. Thanks! All seems to have been installed in the right spot now.

I'll update the [tracking bug](https://bugs.gentoo.org/718060) in Gentoo's bugzilla. If anyone is interested in helping out with further improvement and testing on Gentoo, you can point them there.

The work is not yet done, so it may be useful to leave this issue open for now.

**Comment by Simran-B** [comment]
Looks like your question were answered, closing this ticket therefore. If there's anything you want us to merge into the code base then please open a pull request.
