### ISSUE TITLE
Clarify how require changes in 2.8

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1694]
https://www.arangodb.com/2015/11/foxx-module-resolution-will-change-in-2-8/ describes how global names should eventually be looked for in the base folder of the foxx app. That doesn't seem to be the case because `require('repositories/myrepo')` throws "Error: Cannot find module" out of Function.Module._resolveFilename (/usr/local/Cellar/arangodb/2.8.0/share/arangodb/js/common/bootstrap/modules.js:498:15)

@pluma

**Comment by pekeler** [comment]
So, to make my 2.7 code forwards compatible

```JavaScript
const CURRENT_VERSION = require("org/arangodb/database-version").CURRENT_VERSION;
const PATH = CURRENT_VERSION < 20800 ? '' : '../';
const MyRepo = require(PATH + 'repositories/myrepo');
```

or is there a more elegant solution?

**Comment by pluma** [comment]
@pekeler can you confirm `require("../repositories/myrepo")` doesn't work in 2.7?

**Comment by pluma** [comment]
The Foxx service generator in 2.7 actually correctly specifies the paths in controllers with the ".." prefix for models and repos and the generated services work fine. I've tested this in the 2.7 branch of ArangoDB at pre-2.7.5.

As far as I can tell there is no reason you can't use relative imports in 2.7 to make your code forwards compatible (without needing a version check).

**Comment by pekeler** [comment]
@pluma you're right: `require("../repositories/myrepo")` works fine in 2.7.3, so I can easily prepare my code for 2.8. This wasn't my understanding from that blog post and the release notes. Feel free to close this then.

**Comment by dothebart** [comment]
@pluma can you improve the changelog for others to come? or is this unneccesary?
