### ISSUE TITLE
Homebrew update v2.8.2: dyld: Symbol not found

### ISSUE THREAD

**Issue by terrybleger** [arangodb/arangodb#1730]
Got this error after upgrade it to v2.8.2 via homebrew:
```
 dyld: Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
  9   Referenced from: /usr/local/Cellar/arangodb/2.8.2/sbin/arangod
 10   Expected in: /usr/lib/libstdc++.6.dylib
 11  in /usr/local/Cellar/arangodb/2.8.2/sbin/arangod
```

```
OS X: 10.11.3-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
```

**Comment by dothebart** [comment]
as @baslr and @neunhoef point out in #1735 the clang contained in el capitan doesn't produce usefull binaries. Please use GCC for now, we're still investigating.

**Comment by mikemcquaid** [comment]
I've reverted this version from Homebrew, please install v2.8.1 from there instead.
