### ISSUE TITLE
Error in foxx route, undefined is not a function

### ISSUE THREAD

**Issue by stj** [arangodb/arangodb#1482]
After updating from ArangoDB 2.6.3 to 2.6.7 & 2.6.8 I receive 599 Stream Closed errors in my application tests and this error in ArangoDB server logs

```bash
2015-09-10T16:56:48Z [3732] ERROR Error in foxx route '{ "match" : "/:graph/vertex/:collection/:key", "methods" : [ "delete" ], "constraint" : { "graph" : "/[^/]+/", "collection" : "/[^/]+/", "key" : "/[^/]+/" } }': 'undefined is not a function', Stacktrace:
2015-09-10T16:56:48Z [3732] ERROR TypeError: undefined is not a function
2015-09-10T16:56:48Z [3732] ERROR   at /usr/share/arangodb/js/apps/system/_api/gharial/APP/gharial.js:1600:29
2015-09-10T16:56:48Z [3732] ERROR   at Object.res.action.callback (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:99:5)
2015-09-10T16:56:48Z [3732] ERROR   at /usr/share/arangodb/js/server/modules/org/arangodb/foxx/routing.js:320:17
2015-09-10T16:56:48Z [3732] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)
2015-09-10T16:56:48Z [3732] ERROR   at next (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1326:7)
2015-09-10T16:56:48Z [3732] ERROR   at BaseMiddleware.middleware (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/base_middleware.js:424:5)
2015-09-10T16:56:48Z [3732] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)
2015-09-10T16:56:48Z [3732] ERROR   at routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1330:3)
2015-09-10T16:56:48Z [3732] ERROR   at foxxRouting (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1081:7)
2015-09-10T16:56:48Z [3732] ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)
2015-09-10T16:56:48Z [3732] ERROR   at Object.routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1330:3)
2015-09-10T16:56:48Z [3732] ERROR   at Function.actions.defineHttp.callback (/usr/share/arangodb/js/actions/api-system.js:58:15)
2015-09-10T16:56:48Z [3732] ERROR
```

I have not been able to reproduce this outside of the application tests but will try to create a reproducible test tomorrow.

**Comment by pluma** [comment]
For reference: https://github.com/arangodb/arangodb/blob/devel/js/apps/system/_api/gharial/APP/gharial.js#L1600

Could it be that you're trying to access a collection which is not yet part of the graph at the time you try to access it?

**Comment by jsteemann** [comment]
I thought so too, but I think then the message should have been: 

> TypeError: Cannot read property 'document' of undefined

For example:
```js
g = { 
  foo: { 
    document: function () { } 
  }, 
  bar: { 
    document: function () { } 
  } 
};
```
```
> g["foo"].document(); // ok
> g["bar"].document(); // ok
> g["baz"].document(); // fails
JavaScript exception: TypeError: Cannot read property 'document' of undefined
```

**Comment by stj** [comment]
Downgraded ArangoDB to 2.6.4 where my application tests pass again. Though in 2.6.5 the above error is not logged.

Also realized that the number of 599 responses I get does not match the number tor TypeErrors in the log.

Only see 599 response on PUT requests to _api/collection/{collection_name}[/truncate, /rotate, /unload] and to _api/cursor/{id}.

So far I could not reproduce this in an isolated test.

**Comment by stj** [comment]
[Here](http://pastebin.com/63czTHws) is a python script to reproduce my application issue 599, though no arango error is logged.

To run the script you will have to install the asynchronous tornado framework python.
```
pip install tornado
```
or via your Linux packaging system (it does not work on MS Windows)
This will work against 2.6.4 but fail against anything newer.

**Comment by jsteemann** [comment]
The problem with the Python script posted in pastebin is that the tornado HTTPRequest will by default send the HTTP header `Connection: Close`.
This will invalidate the connection after the first request, so the script fails randomly (depending on how fast the close is actually handled).
You should either open a new connection for each request (note that this will cause performance problems) or add an HTTP header to keep the connection alive:
```python
    req = HTTPRequest(
        url=j([col, 'truncate']),
        headers={ "Connection" : "Keep-Alive" },   # add this
        method='PUT',
        allow_nonstandard_methods=True,
    )
```

**Comment by jsteemann** [comment]
Did the problem with *599 Stream Closed* go away when sending the `Connection: Keep-Alive` header from Python?

**Comment by stj** [comment]
I switched to a curl based client that comes with the tornado framework. The 599 is gone with that client. Not sure if `Connection: Keep-Alive` is a default of curl though.

When I run my application tests now, the foxx route error does not show up in the arangodb logs any more. Guess that was somehow related.

**Comment by jsteemann** [comment]
I am not sure if libcurl sends a `Connection` header, but I think it pools and re-uses connections automatically, so it doesn't really care whether a previous connection has been closed. It will simply open it again.
